user  nobody;
worker_processes  auto;

error_log  /dev/stderr;
pid        /run/nginx.pid;


events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                   '$status $body_bytes_sent "$http_referer" '
                   '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /dev/stdout;

    sendfile        on;

    keepalive_timeout  65;

    gzip on;
    gzip_types application/javascript
        image/svg+xml
        text/css;
    gzip_min_length 100;

    upstream locations_api {
      keepalive 100;
      server locations_api:8000;
    }

    server {
      server_name api.mylocations.local;
      listen 80;
      location / {
        proxy_pass http://locations_api;
      }
    }

    server {
      server_name mylocations.local;
      listen 80;
      location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
      }
    }
}
