version: "3"

services:
  api:
    command: >
      bash -c "alembic upgrade head &&
      sanic my_locations_api:api
      --host=0.0.0.0
      --port=8000
      --reload
      --workers=2"
    env_file: ./.env.dev
    volumes:
      - ./api/my_locations_api:/api/my_locations_api:ro

  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile.dev
      args:
        CUSTOM_DOMAIN: ${CUSTOM_DOMAIN}
    env_file: ./.env.dev
    ports:
      - "${GATEWAY_ADDRESS}:80:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro

  db:
    env_file: ./.env.dev
    volumes:
      - ./db/01-init-test-database.sql:/docker-entrypoint-initdb.d/01-init-test-database.sql
