version: "3"

services:
  api:
    command: >
      bash -c "alembic upgrade head &&
      sanic my_locations_api:api
      --host=0.0.0.0
      --port=8000
      --fast"
    env_file: ./.env.prod

  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile.prod
      args:
        CUSTOM_DOMAIN: ${CUSTOM_DOMAIN}
    env_file: ./.env.prod
    ports:
      - "${GATEWAY_ADDRESS}:80:80"
      - "${GATEWAY_ADDRESS}:443:443"

  db:
    env_file: ./.env.prod
