FROM python:3.11-slim

WORKDIR /api

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN ["pip", "install", "poetry"]

COPY ./api/my_locations_api /api/my_locations_api
COPY ./api/poetry.lock /api/poetry.lock
COPY ./api/pyproject.toml /api/pyproject.toml
COPY ./api/alembic /api/alembic
COPY ./api/alembic.ini /api/alembic.ini
COPY ./api/run-prod.sh /api/start.sh

RUN ["poetry", "install", "--without", "development"]

RUN ["chmod", "+x", "/api/start.sh"]
